// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProzorroDataMining.Data;

#nullable disable

namespace ProzorroDataMining.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260909134718_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProzorroDataMining.Domain.Entities.Tender", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(32)");

                    b.Property<decimal>("BudgetAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BudgetCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(3)")
                        .HasDefaultValue("UAH");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("DateModified")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ProcuringEntityId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProcuringEntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DateCreated")
                        .HasDatabaseName("idx_tenders_date_created");

                    b.HasIndex("ProcuringEntityName")
                        .HasDatabaseName("idx_tenders_entity_name");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_tenders_status");

                    b.HasIndex("Status", "DateCreated")
                        .HasDatabaseName("idx_tenders_status_date");

                    b.ToTable("tenders", (string)null);
                });

            modelBuilder.Entity("ProzorroDataMining.Domain.Entities.TenderAward", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(32)");

                    b.Property<decimal?>("AwardValue")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SupplierId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenderId")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierName")
                        .HasDatabaseName("idx_tender_awards_supplier_name");

                    b.HasIndex("TenderId")
                        .HasDatabaseName("idx_tender_awards_tender_id");

                    b.ToTable("tender_awards", (string)null);
                });

            modelBuilder.Entity("ProzorroDataMining.Domain.Entities.TenderContract", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(32)");

                    b.Property<decimal?>("ContractValue")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(3)")
                        .HasDefaultValue("UAH");

                    b.Property<DateTimeOffset?>("DateSigned")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenderId")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("TenderId")
                        .HasDatabaseName("idx_tender_contracts_tender_id");

                    b.ToTable("tender_contracts", (string)null);
                });

            modelBuilder.Entity("ProzorroDataMining.Domain.Entities.TenderItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("CpvCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CpvDescription")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("TenderId")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<string>("UnitCode")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UnitName")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CpvCode")
                        .HasDatabaseName("idx_tender_items_cpv_code");

                    b.HasIndex("TenderId")
                        .HasDatabaseName("idx_tender_items_tender_id");

                    b.ToTable("tender_items", (string)null);
                });

            modelBuilder.Entity("ProzorroDataMining.Domain.Entities.TenderAward", b =>
                {
                    b.HasOne("ProzorroDataMining.Domain.Entities.Tender", "Tender")
                        .WithMany("Awards")
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("ProzorroDataMining.Domain.Entities.TenderContract", b =>
                {
                    b.HasOne("ProzorroDataMining.Domain.Entities.Tender", "Tender")
                        .WithMany("Contracts")
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("ProzorroDataMining.Domain.Entities.TenderItem", b =>
                {
                    b.HasOne("ProzorroDataMining.Domain.Entities.Tender", "Tender")
                        .WithMany("Items")
                        .HasForeignKey("TenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tender");
                });

            modelBuilder.Entity("ProzorroDataMining.Domain.Entities.Tender", b =>
                {
                    b.Navigation("Awards");

                    b.Navigation("Contracts");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
